backend:
  name: github
  repo: Hess3000/folk-on-the-hill
  branch: gh-pages
media_folder: "imgs/uploads"
collections:
  - label: "Edit sections of Folk on the Hill below"
    name: "pages"
    files:
      - label: "Line-up"
        name: "lineup"
        file: "_data/lineup.yml"
        fields:
          - {label: Act 1, name: lineup_artist_1, widget: string, required: false}
          - {label: Act 2, name: lineup_artist_2, widget: string, required: false}
          - {label: Act 3, name: lineup_artist_3, widget: string, required: false}
          - {label: Act 4, name: lineup_artist_4, widget: string, required: false}
          - {label: Act 5, name: lineup_artist_5, widget: string, required: false}
          - {label: Act 6, name: lineup_artist_6, widget: string, required: false}
  		- label: "Locations Page"
        name: "locations"
        file: "site/content/locations.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}