backend:
  name: github
  repo: Hess3000/folk-on-the-hill
  branch: gh-pages
media_folder: "imgs/uploads"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Line up"
        name: "lineup"
        file: "_data/lineup.yml"
        fields:
          - {label: Act 1, name: lineup_artist_1:, widget: string, required: false}
          