backend:
  name: github
  repo: Hess3000/folk-on-the-hill
  branch: gh-pages
media_folder: "imgs/uploads"
collections:
  - label: "Edit sections of Folk on the Hill below"
    name: "pages"
    files:
      - label: "Saturday line-up"
        name: "lineup"
        file: "_data/saturday_lineup.yml"
        fields:
          - {label: Act 1, name: lineup_artist_1, widget: string, required: false}
          - {label: Act 2, name: lineup_artist_2, widget: string, required: false}
          - {label: Act 3, name: lineup_artist_3, widget: string, required: false}
          - {label: Act 4, name: lineup_artist_4, widget: string, required: false}
          - {label: Act 5, name: lineup_artist_5, widget: string, required: false}
          - {label: Act 6, name: lineup_artist_6, widget: string, required: false}
      